server:
  port: 7987
spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  application:
    name: debug4j-server
  web:
    resources:
      static-locations: "classpath:/dist"

debug4j:
  key: k4ln
  socket-port: 7988
#  developer: true

sa-token:
  http-basic: 'k4ln:123456'
  max-login-count: -1

